name: Publish Package to npmjs
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm i
          npm run test
          npm run prepack
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_FLUIDUI_SVELTE_TOKEN }}
  # npm publish --provenance --access public
