import { contrastRatio, generateRamp, formatOklch, rampStops, type Ramp } from './color';

export const colorRoles = [
	'neutral',
	'primary',
	'secondary',
	'tertiary',
	'success',
	'warning',
	'info',
	'error'
] as const;

export type ColorRole = (typeof colorRoles)[number];

export const roleLabels: Record<ColorRole, string> = {
	neutral: 'Neutral',
	primary: 'Primary',
	secondary: 'Secondary',
	tertiary: 'Tertiary',
	success: 'Success',
	warning: 'Warning',
	info: 'Info',
	error: 'Error'
};

export const radiusOptions = [
	{ id: 'none', label: 'None', base: 0 },
	{ id: 'small', label: 'Small', base: 0.25 },
	{ id: 'medium', label: 'Medium', base: 0.375 },
	{ id: 'large', label: 'Large', base: 0.5 },
	{ id: 'full', label: 'Round', base: 0.75 }
] as const;

export type RadiusId = (typeof radiusOptions)[number]['id'];

export const isRadiusId = (value: unknown): value is RadiusId =>
	typeof value === 'string' && radiusOptions.some((option) => option.id === value);

export type Theme = {
	name: string;
	colors: Record<ColorRole, string>;
	radius: RadiusId;
};

/** The four radius tokens keep a fixed ratio, so one control retunes the set. */
const radiusScale = (base: number) => ({
	'--radius-sm': base * 0.66,
	'--radius-md': base,
	'--radius-lg': base * 1.33,
	'--radius-xl': base * 2
});

const resolveRadius = (radius: RadiusId) =>
	radiusOptions.find((option) => option.id === radius) ?? radiusOptions[2];

export const buildRamps = (theme: Theme): Record<ColorRole, Ramp> =>
	Object.fromEntries(
		colorRoles.map((role) => [
			role,
			generateRamp(theme.colors[role], { neutral: role === 'neutral' })
		])
	) as Record<ColorRole, Ramp>;

/**
 * Flattens a theme into the exact custom properties fluidui.css reads. The same
 * map drives the live preview and the exported stylesheet, so what a user sees
 * on the page is what they take away.
 */
export const buildTokens = (theme: Theme): Record<string, string> => {
	const ramps = buildRamps(theme);
	const tokens: Record<string, string> = {};

	for (const role of colorRoles) {
		for (const stop of rampStops) {
			tokens[`--color-${role}-${stop}`] = formatOklch(ramps[role][stop]);
		}
	}

	const lightForeground = ramps.neutral[50];
	const darkForeground = ramps.neutral[950];
	for (const role of colorRoles) {
		if (role === 'neutral') continue;
		const background = ramps[role][500];
		const foreground =
			contrastRatio(lightForeground, background) >= contrastRatio(darkForeground, background)
				? lightForeground
				: darkForeground;
		tokens[`--on-${role}`] = formatOklch(foreground);
	}

	for (const [token, value] of Object.entries(radiusScale(resolveRadius(theme.radius).base))) {
		tokens[token] = `${Number(value.toFixed(4))}rem`;
	}

	return tokens;
};

export const applyTheme = (theme: Theme, target: HTMLElement) => {
	for (const [token, value] of Object.entries(buildTokens(theme))) {
		target.style.setProperty(token, value);
	}
};

export const clearTheme = (theme: Theme, target: HTMLElement) => {
	for (const token of Object.keys(buildTokens(theme))) {
		target.style.removeProperty(token);
	}
};

const escapeRegularExpression = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/**
 * Writes a theme directly into the canonical Fluid source stylesheet. Keeping
 * the component rules in that source avoids a second, drifting copy of the
 * `.fluid-*` contract in the documentation app.
 */
export const themeToFluidCss = (theme: Theme, fluidCss: string): string => {
	let themedCss = fluidCss;

	for (const [token, value] of Object.entries(buildTokens(theme))) {
		const declaration = new RegExp(`(^[\\t ]*)${escapeRegularExpression(token)}:\\s*[^;]+;`, 'm');

		if (!declaration.test(themedCss)) {
			throw new Error(`The canonical Fluid stylesheet is missing ${token}.`);
		}

		themedCss = themedCss.replace(declaration, `$1${token}: ${value};`);
	}

	return `/* ${theme.name} — generated by the Fluid UI theme editor */\n${themedCss.trim()}\n`;
};

/** A lightweight override for projects that already keep fluidui.css locally. */
export const themeToCss = (theme: Theme): string => {
	const ramps = buildRamps(theme);
	const radius = radiusScale(resolveRadius(theme.radius).base);
	const tokens = buildTokens(theme);

	const rampBlock = colorRoles
		.map((role) =>
			rampStops
				.map((stop) => `\t--color-${role}-${stop}: ${formatOklch(ramps[role][stop])};`)
				.join('\n')
		)
		.join('\n\n');

	const radiusBlock = Object.entries(radius)
		.map(([token, value]) => `\t${token}: ${Number(value.toFixed(4))}rem;`)
		.join('\n');
	const foregroundBlock = colorRoles
		.filter((role) => role !== 'neutral')
		.map((role) => `\t--on-${role}: ${tokens[`--on-${role}`]};`)
		.join('\n');

	return `/* ${theme.name} — generated by the Fluid UI theme editor */
@import './fluidui.css';

@theme {
${rampBlock}

${radiusBlock}
}

:root {
${foregroundBlock}
}
`;
};
